import type { Recipe, Profile } from './types'

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Rührei mit Toast',
    description: 'Ein schnelles, einfaches Frühstück oder Abendessen.',
    timeMinutes: 10,
    portions: 1,
    chopping: 'none',
    usesStove: true,
    usesOven: false,
    requiresMultitasking: false,
    ingredientCount: 4,
    panCount: 1,
    canWalkAway: false,
    tags: [],
    ingredients: [
      { name: 'Eier', amount: '2', unit: 'Stück' },
      { name: 'Butter', amount: '1', unit: 'TL' },
      { name: 'Salz', amount: '1', unit: 'Prise' },
      { name: 'Toast', amount: '2', unit: 'Scheiben' },
    ],
    steps: [
      { text: 'Eier in eine Schüssel aufschlagen und mit einer Gabel verquirlen. Eine Prise Salz dazugeben.' },
      { text: 'Butter in einer Pfanne bei mittlerer Hitze schmelzen lassen.', durationSeconds: 60, checkText: 'Die Butter soll schmelzen, aber nicht bräunen.' },
      { text: 'Eier in die Pfanne gießen.' },
      { text: 'Mit einem Holzlöffel langsam rühren, bis die Eier cremig aussehen.', durationSeconds: 90 },
      { text: 'Pfanne vom Herd nehmen – die Eier garen durch die Restwärme fertig. Toast toasten.', isStopPoint: true },
      { text: 'Rührei auf dem Toast servieren.' },
    ],
    substitutions: [
      { ingredient: 'Butter', substitute: 'Margarine oder ein Spritzer Öl' },
    ],
    fixes: [
      { problem: 'Eier werden zu fest', solution: 'Sofort vom Herd nehmen – die Pfanne ist noch heiß genug.' },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Nudeln mit Butter und Parmesan',
    description: 'Simpel, sättigend und immer lecker.',
    timeMinutes: 15,
    portions: 2,
    chopping: 'none',
    usesStove: true,
    usesOven: false,
    requiresMultitasking: false,
    ingredientCount: 4,
    panCount: 1,
    canWalkAway: true,
    tags: ['vegetarisch'],
    ingredients: [
      { name: 'Nudeln', amount: '200', unit: 'g' },
      { name: 'Butter', amount: '2', unit: 'EL' },
      { name: 'Parmesan, gerieben', amount: '4', unit: 'EL' },
      { name: 'Salz', amount: '1', unit: 'TL' },
    ],
    steps: [
      { text: 'Einen Topf mit Wasser füllen und bei hoher Hitze zum Kochen bringen.', durationSeconds: 300, checkText: 'Das Wasser muss sprudeln.' },
      { text: 'Salz und Nudeln ins kochende Wasser geben und umrühren.', isStopPoint: true },
      { text: 'Nudeln laut Packungsanweisung kochen (meist 8–10 Minuten).', durationSeconds: 480, checkText: 'Eine Nudel herausnehmen und probieren – sie soll weich sein.' },
      { text: 'Nudeln in ein Sieb abgießen und abtropfen lassen.' },
      { text: 'Nudeln zurück in den Topf geben. Butter und Parmesan dazugeben und alles gut umrühren.' },
      { text: 'Sofort servieren und genießen.' },
    ],
    substitutions: [
      { ingredient: 'Parmesan', substitute: 'Geriebener Gouda oder Emmentaler' },
      { ingredient: 'Butter', substitute: 'Olivenöl' },
    ],
    fixes: [
      { problem: 'Nudeln kleben zusammen', solution: 'Etwas mehr Butter oder Öl dazugeben und gut umrühren.' },
      { problem: 'Zu fade', solution: 'Mehr Salz oder etwas Zitronensaft dazugeben.' },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Tomatensuppe aus der Dose',
    description: 'Wärmend und in wenigen Minuten fertig.',
    timeMinutes: 10,
    portions: 2,
    chopping: 'none',
    usesStove: true,
    usesOven: false,
    requiresMultitasking: false,
    ingredientCount: 2,
    panCount: 1,
    canWalkAway: false,
    tags: ['vegetarisch', 'weiche-speisen'],
    ingredients: [
      { name: 'Tomatensuppe (Dose oder Tetra Pak)', amount: '1', unit: 'Dose' },
      { name: 'Wasser oder Milch', amount: '1', unit: 'Dose (zum Auffüllen)' },
    ],
    steps: [
      { text: 'Dosensuppe in einen Topf gießen.' },
      { text: 'Eine Dose Wasser oder Milch dazugeben (die Menge steht auf der Packung). Umrühren.' },
      { text: 'Bei mittlerer Hitze erwärmen und dabei gelegentlich rühren.', durationSeconds: 300, checkText: 'Die Suppe soll heiß sein, aber nicht kochen.' },
      { text: 'In Schüsseln gießen und mit Brot servieren.' },
    ],
    substitutions: [],
    fixes: [
      { problem: 'Suppe zu dick', solution: 'Noch etwas Wasser dazugeben und umrühren.' },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Käsebrot mit Tomate',
    description: 'Kein Herd nötig – perfekt für jeden Tag.',
    timeMinutes: 5,
    portions: 1,
    chopping: 'basic',
    usesStove: false,
    usesOven: false,
    requiresMultitasking: false,
    ingredientCount: 4,
    panCount: 0,
    canWalkAway: true,
    tags: ['vegetarisch', 'kein-herd'],
    ingredients: [
      { name: 'Brot', amount: '2', unit: 'Scheiben' },
      { name: 'Butter', amount: '1', unit: 'EL' },
      { name: 'Käse', amount: '2', unit: 'Scheiben' },
      { name: 'Tomate', amount: '1', unit: 'Stück' },
    ],
    steps: [
      { text: 'Brot mit Butter bestreichen.' },
      { text: 'Käse auf das Brot legen.' },
      { text: 'Tomate in Scheiben schneiden und auf den Käse legen.', checkText: 'Vorsicht beim Schneiden – Finger weghalten.' },
      { text: 'Fertig! Mit etwas Salz und Pfeffer würzen nach Geschmack.' },
    ],
    substitutions: [
      { ingredient: 'Tomate', substitute: 'Gurke oder Paprika' },
      { ingredient: 'Käse', substitute: 'Aufschnitt oder Frischkäse' },
    ],
    fixes: [],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Haferbrei',
    description: 'Ein wärmendes, nahrhaftes Frühstück.',
    timeMinutes: 10,
    portions: 1,
    chopping: 'none',
    usesStove: true,
    usesOven: false,
    requiresMultitasking: false,
    ingredientCount: 4,
    panCount: 1,
    canWalkAway: false,
    tags: ['vegetarisch', 'weiche-speisen', 'frühstück'],
    ingredients: [
      { name: 'Haferflocken', amount: '50', unit: 'g' },
      { name: 'Milch oder Wasser', amount: '200', unit: 'ml' },
      { name: 'Salz', amount: '1', unit: 'Prise' },
      { name: 'Honig oder Marmelade', amount: '1', unit: 'TL' },
    ],
    steps: [
      { text: 'Milch (oder Wasser) in einem kleinen Topf bei mittlerer Hitze erwärmen.' },
      { text: 'Haferflocken und eine Prise Salz dazugeben und umrühren.' },
      { text: 'Unter gelegentlichem Rühren ca. 3–5 Minuten köcheln lassen, bis der Brei dick wird.', durationSeconds: 240 },
      { text: 'In eine Schüssel geben und mit Honig oder Marmelade süßen.' },
    ],
    substitutions: [
      { ingredient: 'Milch', substitute: 'Pflanzenmilch (Hafer, Mandel) oder Wasser' },
    ],
    fixes: [
      { problem: 'Zu dick', solution: 'Noch etwas Milch oder Wasser einrühren.' },
      { problem: 'Klumpen', solution: 'Kräftig rühren.' },
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
]

export const DEFAULT_PROFILE: Profile = {
  portions: 1,
  maxTimeMinutes: 30,
  allergies: [],
  dislikes: [],
  equipment: ['Herd', 'Toaster'],
  notificationHour: 10,
  wantsShoppingList: false,
  shopDayAhead: false,
}
